version: "3"
services:
  web:
    build: .
    environment:
      JWT_SECRET: jwt-secret
      DB_URL: jdbc:mysql://db:3306/chat_db
      DB_USER: root
      DB_PASSWORD: douglas110291
    ports:
      - "8080:8080"
    restart: always
    networks:
      - mysql-phpmyadmin
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - mysql-phpmyadmin
    restart: always
    ports:
      - "8081:80"

  db:
    image: mysql
    volumes:
      - chat_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: douglas110291
    ports:
      - "3307:3306"
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  chat_data: