version: "3"
services:
  web:
    build: .
    environment:
      JWT_SECRET: jwt-secret
      DB_URL: jdbc:mysql://db:3307/douglasmotta_chat_db
      DB_USER: douglasmotta_chat
      DB_PASSWORD: NVAq&k%6NAaH
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - chat_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: douglas110291
      MYSQL_DATABASE: database_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - mysql-phpmyadmin
    restart: always
    ports:
      - "8081:80"


networks:
  mysql-phpmyadmin:

volumes:
  chat_db_data: