version: "3"
services:
  web:
    build: .
    environment:
      JWT_SECRET: jwt-secret
      DB_URL: jdbc:mysql://db:3306/douglasmotta_chat_db
      DB_USER: root
      DB_PASSWORD: h^U&98wqkP^8
      DB_PORT: 8080
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - chat_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: h^U&98wqkP^8
    ports:
      - "3306:3306"

volumes:
  chat_db_data: