version: "3"
services:
  web:
    build: .
    environment:
      JWT_SECRET: jwt-secret
      DB_URL: jdbc:mysql://db:3306/douglasmotta_chat_db
      DB_USER: douglasmotta_chat
      DB_PASSWORD: NVAq&k%6NAaH
    ports:
      - "8080:8080"
    restart: always