version: "3"
services:
  web:
    build: .
    environment:
      JWT_SECRET: jwt-secret
      DB_URL: jdbc:mysql://db:3307/douglasmotta_chat_db
      DB_USER: douglasmotta_chat
      DB_PASSWORD: NVAq&k%6NAaH
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - chat_db_data:/var/lib/mysql
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: douglas110291
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - my-network
    container_name: pma
    depends_on:
      - db
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: douglas110291
      PMA_HOST: db
      PMA_PORT: 3307
    restart: always
    ports:
      - "8081:80"

# Define networks
networks:
  my-network:

volumes:
  chat_db_data: