version: "3"
services:
  web:
    build: .
    environment:
      JWT_SECRET: jwt-secret
      DB_URL: jdbc:mysql://db:3307/douglasmotta_chat_db
      DB_USER: douglasmotta_chat
      DB_PASSWORD: NVAq&k%6NAaH
      DB_PORT: 3307
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - chat_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: NVAq&k%6NAaH
    ports:
      - "3307:3306"

volumes:
  chat_db_data: