version: "3"
services:
  nginx:
    container_name: chat-nginx
    image: nginx:1.25
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    networks:
      - backend
  web:
    build: .
    container_name: app
    environment:
      JWT_SECRET: jwt-secret
      DB_URL: jdbc:mysql://db:3306/chat_db
      DB_USER: root
      DB_PASSWORD: douglas110291
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - backend
    restart: always
    ports:
      - "8082:80"

  db:
    image: mysql:8
    volumes:
      - chat_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: douglas110291
    ports:
      - "3307:3306"
    networks:
      - backend

networks:
  backend:

volumes:
  chat_data: